---
version: '3'

services:
  tinytuya2mqtt:
    image: ghcr.io/mafrosis/tinytuya2mqtt:dev
    restart: unless-stopped
    build:
      context: .
    environment:
      - DEBUG
    volumes:
      - ./snapshot.json:/snapshot.json:ro
      - ./tinytuya2mqtt.ini:/tinytuya2mqtt.ini:ro
